# Generated by Django 4.1.7 on 2023-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_extendeduser_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
