# Generated by Django 4.1.7 on 2023-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_extendeduser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='marital_status',
        ),
    ]
